description: "File a bug report"
labels: [bug]
assignees: "JeffJrShim"
name: "Bug Report"
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to make an issue!
        If you want general support please ask in my server: https://discord.gg/RSAetqdhRU
  - type: input
    id: discord
    attributes:
      description: "To either contact you to ask you more about the details, and/or to inform you that the bug has been fixed."
    validations:
      required: true
  - type: dropdown
    id: cog-name
    attributes:
      label: "What cog is this bug report for?"
      options:
        - BreadFact
        - FakeMod
        - LeaveOnBlacklist
        - OwnerManagement
        - RandomNoa
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      description: "Please go into as much detail as possible and, if you can, show steps to reproduce it. If there's an error, paste it in the next box below."
      label: "Describe the bug"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      description: "Please copy and paste any relevant log output either from the console or using the `[p]traceback` command. This will be automatically formatted into code, so no need for backticks."
      label: "Please paste there error here, if any."
      render: python
    validations:
      required: false
