description: "File a feature request"
labels: [enhancement]
name: "Feature request"
assignees: JeffJrShim
body:
  - type: input
    id: discord
    attributes:
      label: "Discord User Information"
      description: "To either contact you to ask you more about the details, and/or to inform you that the feature has been implemented. Feel free to leave this blank if you don't feel like sharing it."
    validations:
      required: false
  - type: dropdown
    id: cog-name
    attributes:
      label: "What cog is this feature request for?"
      options:
        - BreadFact
        - FakeMod
        - LeaveOnBlacklist
        - OwnerManagement
        - RandomNoa
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: "Describe the feature request in as much detail as possible"
      placeholder: "The more information the better!"
    validations:
      required: true
