description: "Feature Requests!"
labels: ["type: enhancement"]
name: "Feature request"
body: yaml 
  - type
    id:cog-name
    attributes:
      label:What cog is this feature request for?
      options:
        - RandomNoa
        - FakeMod
  - type:textarea
    id:desc
    attributes:
      label:Describe the feature request in as much detail as possible
      placeholder:"The more information the better!"
  - type:checkboxes
    id:agreeeee
    attributes:
      label:Have you done the below?
      description:It is important to finish the below, before submitting this issue.
      options:
      - label:I have already discussed this with the owner of the repository JeffJrShim#2396, before filing this feature request.
      - label:I have confirmed that my feature request isn't already available on the said cog. 
